In [17]:
import numpy as np
def ijmatrix(m, n):
    if m < 0 or n < 0:
        return None
    return np.arange(m) * np.arange(n).reshape(m,1)

ijmatrix(5,5)
    

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [ ]:
def normalize_cols(m):
    factor = m.sum(0).reshape(1, m.shape[1])
    return m / factor

normalize_cols(np.array([
    [1.0, 2.0, 6.0, 4.0],
    [3.0, 4.0, 3.0, 7.0],
    [1.0, 4.0, 6.0, 9.0]]))

[ 5. 10. 15. 20.]


array([[0.2 , 0.2 , 0.4 , 0.2 ],
       [0.6 , 0.4 , 0.2 , 0.35],
       [0.2 , 0.4 , 0.4 , 0.45]])

In [47]:
def normalize_rows(m):
    factor = m.sum(1).reshape(m.shape[0], 1)
    return m / factor

normalize_rows(np.array([
    [1.0, 2.0, 6.0, 4.0],
    [3.0, 4.0, 3.0, 7.0],
    [1.0, 4.0, 6.0, 9.0]]))

array([[0.07692308, 0.15384615, 0.46153846, 0.30769231],
       [0.17647059, 0.23529412, 0.17647059, 0.41176471],
       [0.05      , 0.2       , 0.3       , 0.45      ]])

In [128]:
np.array([[1,2,3,], [1,2,3,]]).size

6

In [51]:
def absm(m):
    return (m + np.absolute(m)) / 2

absm(np.array([[1, -1, -1], [3, -1, 2]]))

array([[1., 0., 0.],
       [3., 0., 2.]])

In [66]:
def sum_prod(m1, m2):
    return m1.dot(m2).sum()

sum_prod(np.array([[1, -1, -1], [3, -1, 2]]), np.array([[1, -1, -1], [3, -1, 2]]).T)

21

In [59]:
a = np.array([[1, -1, -1], [3, -1, 2]])
a.dot(a.T)

array([[ 3,  2],
       [ 2, 14]])

In [120]:
file = "Donald Duck ITA 9.3 8.9 9.7 9.7 9.8\n\
Mickey Mouse ITA 9.0 9.0 9.0 9.2 9.5\n\
Bugs Bunny USA 8.4 8.7 8.5 8.6 9.0\n\
Daffy Duck RUS 8.3 8.8 9.5 9.6 9.0\n\
Charlie Brown GRB 8.2 8.9 8.9 8.6 9.3\n"

M = []
competitors = []
for line in file.split('\n'):
    if line == "":
        continue
    fields = line.split(' ')
    competitors.append(fields[0:3])
    points = np.array(list(map(float, fields[3:])))
    M.append(points)

M = np.array(M)
M.sort()
# We ignore best and worst scores for each player
M = M[:, 1:-1]
# We sum each player score
scores = M.sum(1)

winners = (-scores).argsort()
print(scores)
winners
list(map(lambda x: competitors[x], winners[0:3]))
# The final ranking for the best 3 competitors: consider that for computing the final records, the
# highest and lowest evaluations are ignored and the score is determined by the sum of the remaining
# 3 values.





[28.7 27.2 25.8 27.3 26.4]


[['Donald', 'Duck', 'ITA'],
 ['Daffy', 'Duck', 'RUS'],
 ['Mickey', 'Mouse', 'ITA']]